### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [fastogt/fastotv#38]
Hi, i am a graphic designer who loves contributing logos to opensource projects. If you like, i contribute a logo for this project too :).

Best regards,
Dee

**Comment by topilski** [comment]
Hi, sure, you can try.

**Comment by dee-y** [comment]
Hi what do you think of these? any improvements?

![fastotv-01](https://user-images.githubusercontent.com/36637989/43566672-25a07b08-9627-11e8-9ea5-c329af6ae48d.png)

**Comment by topilski** [comment]
I like first one

**Comment by topilski** [comment]
@dee-y good job!

**Comment by dee-y** [comment]
Alright i will work with the first one. Are there any logo dimensions/sizes you would like me to export? or i export according to the universal standard sizes and type

**Comment by dee-y** [comment]
I have made a pull request with all the necessary files you need. Please you can contact me anytime if you need further assistance. Cheers!

**Comment by topilski** [comment]
Thank you!

**Comment by topilski** [comment]
Hi @dee-y, can you create images for application, i need 64x64 and 512x512 png files.

**Comment by dee-y** [comment]
Owk am on it.

**Comment by dee-y** [comment]
64x64 px
![64 x 64 px](https://user-images.githubusercontent.com/36637989/43806615-90d4a808-9a9c-11e8-912a-f5ec09d147f0.png)

512x512px
![512 x 512 px](https://user-images.githubusercontent.com/36637989/43806616-91244f84-9a9c-11e8-8334-3051cbc254cf.png)

**Comment by topilski** [comment]
Thank you friend!

**Comment by dee-y** [comment]
Anytime!
