### ISSUE TITLE
Flashing on startup (unstable)

### ISSUE THREAD

**Issue by mathiassond** [fastogt/fastotv#41]
a black screen flashes when i start fastotv

**Comment by topilski** [comment]
Hi @mathiassond , thank you for issue, on which os?

**Comment by BoostRacerKing** [comment]
on Ubuntu 19.04 and Kubuntu 19.04

**Comment by topilski** [comment]
Please try `SDL_VIDEO_X11_XVIDMODE=0 fastotv`

**Comment by mathiassond** [comment]
I'm running ubuntu 18.04. SDL_VIDEO_X11_XVIDMODE=0 fastotv work for me, it allow me to switch channel without crash also

**Comment by topilski** [comment]
@mathiassond cool, thank you for your feedback, in next release SDL_VIDEO_X11_XVIDMODE variable will be injected into app

**Comment by topilski** [comment]
We updated the new release, you can try how it works now.

**Comment by mathiassond** [comment]
thank you, i've installed v 1.21 and it seem to be good so far:)
