### ISSUE TITLE
Channels not showing up in list

### ISSUE THREAD

**Issue by darkx239** [fastogt/fastotv#42]
Only 10 channels in non fullscreen and fullscreen has 11 I have selected more than 12 channels and it will not show them

**Comment by topilski** [comment]
Hi @darkx239 , what is your os?

**Comment by darkx239** [comment]
Windows 10 x64

**Comment by topilski** [comment]
Hi @darkx239 fixed in 1.2.2 version, please try how it works.

**Comment by topilski** [comment]
ping
