### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by electron64** [fastogt/fastotv#45]
Hi i tried to build and i get an error.
i follwed the steps but can t get ride of the error.
can you help me to fix it please?

`85.0% Start signing path: /opt/fastotv/FastoTV
85.0% Please implement code sign for: linux, application path: /opt/fastotv/FastoTV
CMake Error at /home/nono/Bureau/fastotv/build/build_linux/src/cmake_install.cmake:51 (file):
  file INSTALL cannot find
  "/home/nono/Bureau/fastotv/build/build_linux/build/bin/FastoTV".
Call Stack (most recent call first):
  /home/nono/Bureau/fastotv/build/build_linux/cmake_install.cmake:37 (include)
  

CPack Error: Error when generating package: fastotv
85.0% CPack: Create package using TGZ
85.0% CPack: Install projects
85.0% CPack: - Install project: FastoTV
85.0% Start signing path: /home/nono/Bureau/fastotv/build/build_linux/_CPack_Packages/Linux/TGZ/fastotv-1.5.2-x86_64-d4e1b69/opt/fastotv/FastoTV
85.0% Please implement code sign for: linux, application path: /home/nono/Bureau/fastotv/build/build_linux/_CPack_Packages/Linux/TGZ/fastotv-1.5.2-x86_64-d4e1b69/opt/fastotv/FastoTV
CMake Error at /home/nono/Bureau/fastotv/build/build_linux/src/cmake_install.cmake:51 (file):
  file INSTALL cannot find
  "/home/nono/Bureau/fastotv/build/build_linux/build/bin/FastoTV".
Call Stack (most recent call first):
  /home/nono/Bureau/fastotv/build/build_linux/cmake_install.cmake:37 (include)
  

CPack Error: Error when generating package: fastotv
100.0% Building finished successfully file_names: ['/home/nono/Bureau/fastotv/build/build_linux/SET.deb', '/home/nono/Bureau/fastotv/build/build_linux/SET.rpm', '/home/nono/Bureau/fastotv/build/build_linux/SET.tar.gz']`

**Comment by topilski** [comment]
also git submodule update --init --recursive

**Comment by electron64** [comment]
I did it, still the same error.

**Comment by topilski** [comment]
What os?

**Comment by electron64** [comment]
ubuntu 18.04, 
yes i used python3 build.py ..

**Comment by topilski** [comment]
can you go to folder build_linux and start ninja command

**Comment by topilski** [comment]
Did you started build_env.py script?

**Comment by electron64** [comment]
yes i did , i followed the steps in the wiki

**Comment by electron64** [comment]
sorry but can you give the command for ninja

**Comment by topilski** [comment]
simple `ninja`

**Comment by electron64** [comment]
ok, here is the log 

`[1/1] Linking CXX executable build/bin/FastoTV
FAILED: build/bin/FastoTV 
: && /usr/bin/c++   -fPIC -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -Wall -Wextra -pedantic -Wswitch-enum -Wsuggest-override -O3 -DNDEBUG   src/CMakeFiles/FastoTV.dir/client/tv_player_main.cpp.o src/CMakeFiles/FastoTV.dir/client/types.cpp.o src/CMakeFiles/FastoTV.dir/client/playlist_entry.cpp.o src/CMakeFiles/FastoTV.dir/client/ioservice.cpp.o src/CMakeFiles/FastoTV.dir/client/utils.cpp.o src/CMakeFiles/FastoTV.dir/client/player.cpp.o src/CMakeFiles/FastoTV.dir/client/playlist_window.cpp.o src/CMakeFiles/FastoTV.dir/client/programs_window.cpp.o src/CMakeFiles/FastoTV.dir/client/load_config.cpp.o src/CMakeFiles/FastoTV.dir/client/cmdutils.cpp.o src/CMakeFiles/FastoTV.dir/client/inner/inner_tcp_server.cpp.o src/CMakeFiles/FastoTV.dir/client/inner/inner_tcp_handler.cpp.o src/CMakeFiles/FastoTV.dir/client/commands.cpp.o src/CMakeFiles/FastoTV.dir/client/events/network_events.cpp.o src/CMakeFiles/FastoTV.dir/client/bandwidth/tcp_bandwidth_client.cpp.o src/CMakeFiles/FastoTV.dir/client/inputs/lirc_input_client.cpp.o  -o build/bin/FastoTV  -rdynamic /usr/local/lib/libfastoplayer.a /usr/local/lib/libfastoplayer_media.a /usr/local/lib/libfastotv_protocol.a /usr/local/lib/libavdevice.a /usr/local/lib/libavformat.a /usr/local/lib/libavfilter.a /usr/local/lib/libavcodec.a /usr/local/lib/libavutil.a /usr/local/lib/libswscale.a /usr/local/lib/libswresample.a /usr/local/lib/libcommon_ev.a /usr/local/lib/libev.a /usr/local/lib/libcommon.a /usr/local/lib/libjson-c.a build/lib/libinih.a /usr/lib/x86_64-linux-gnu/liblirc_client.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbz2.so /usr/lib/x86_64-linux-gnu/libz.so /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a /usr/local/lib/libSDL2.a /usr/local/lib/libSDL2_image.a /usr/local/lib/libSDL2_ttf.a /usr/local/lib/libev.a /usr/local/lib/libcpuid.a -lpthread -ldl -lm /usr/lib/x86_64-linux-gnu/libva-drm.so /usr/lib/x86_64-linux-gnu/libva-x11.so /usr/lib/x86_64-linux-gnu/libSM.so /usr/lib/x86_64-linux-gnu/libICE.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libXext.so /usr/lib/x86_64-linux-gnu/libasound.so -lvdpau -lva /usr/local/lib/libcommon.a /usr/local/lib/libjson-c.a /usr/lib/x86_64-linux-gnu/liblirc_client.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbz2.so /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a /usr/local/lib/libSDL2.a /usr/local/lib/libSDL2_image.a /usr/local/lib/libSDL2_ttf.a /usr/local/lib/libcpuid.a -lpthread -ldl -lm /usr/lib/x86_64-linux-gnu/libva-drm.so /usr/lib/x86_64-linux-gnu/libva-x11.so /usr/lib/x86_64-linux-gnu/libSM.so /usr/lib/x86_64-linux-gnu/libICE.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libXext.so /usr/lib/x86_64-linux-gnu/libasound.so -lvdpau -lva && cd /home/nono/fastotv/build/build_linux/src && /usr/bin/strip --strip-unneeded /home/nono/fastotv/build/build_linux/build/bin/FastoTV
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_initFontMetrics » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:422 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:423 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:424 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:425 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:426 : référence indéfinie vers « FT_MulFix »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o):/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:427 : encore plus de références indéfinies suivent vers « FT_MulFix »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « Find_Glyph » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:880 : référence indéfinie vers « FT_Get_Char_Index »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « Load_Glyph » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:552 : référence indéfinie vers « FT_Load_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:633 : référence indéfinie vers « FT_Get_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:634 : référence indéfinie vers « FT_Stroker_New »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:650 : référence indéfinie vers « FT_Render_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:846 : référence indéfinie vers « FT_Done_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:627 : référence indéfinie vers « FT_Outline_Transform »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:638 : référence indéfinie vers « FT_Stroker_Set »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:639 : référence indéfinie vers « FT_Glyph_Stroke »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:640 : référence indéfinie vers « FT_Stroker_Done »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:642 : référence indéfinie vers « FT_Glyph_To_Bitmap »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:644 : référence indéfinie vers « FT_Done_Glyph »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_SizeUTF8_Internal » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1205 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_CloseFont » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:889 : référence indéfinie vers « FT_Done_Face »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_Init » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:225 : référence indéfinie vers « FT_Init_FreeType »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_OpenFontIndexRW » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:316 : référence indéfinie vers « FT_Open_Face »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:355 : référence indéfinie vers « FT_Set_Charmap »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:397 : référence indéfinie vers « FT_Select_Size »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:376 : référence indéfinie vers « FT_Set_Char_Size »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Solid » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1345 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Shaded » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1522 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Blended » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1679 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Blended_Wrapped » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1944 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_GetFontKerningSize » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:2093 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o):/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:2125 : encore plus de références indéfinies suivent vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_GlyphIsProvided » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1123 : référence indéfinie vers « FT_Get_Char_Index »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_Quit » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:2079 : référence indéfinie vers « FT_Done_FreeType »
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.`

**Comment by topilski** [comment]
Ok, i see problem thank you, you can use prebuild versions on the website.

**Comment by electron64** [comment]
ok, thank you. here is the log 

`[1/1] Linking CXX executable build/bin/FastoTV
FAILED: build/bin/FastoTV 
: && /usr/bin/c++   -fPIC -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -Wall -Wextra -pedantic -Wswitch-enum -Wsuggest-override -O3 -DNDEBUG   src/CMakeFiles/FastoTV.dir/client/tv_player_main.cpp.o src/CMakeFiles/FastoTV.dir/client/types.cpp.o src/CMakeFiles/FastoTV.dir/client/playlist_entry.cpp.o src/CMakeFiles/FastoTV.dir/client/ioservice.cpp.o src/CMakeFiles/FastoTV.dir/client/utils.cpp.o src/CMakeFiles/FastoTV.dir/client/player.cpp.o src/CMakeFiles/FastoTV.dir/client/playlist_window.cpp.o src/CMakeFiles/FastoTV.dir/client/programs_window.cpp.o src/CMakeFiles/FastoTV.dir/client/load_config.cpp.o src/CMakeFiles/FastoTV.dir/client/cmdutils.cpp.o src/CMakeFiles/FastoTV.dir/client/inner/inner_tcp_server.cpp.o src/CMakeFiles/FastoTV.dir/client/inner/inner_tcp_handler.cpp.o src/CMakeFiles/FastoTV.dir/client/commands.cpp.o src/CMakeFiles/FastoTV.dir/client/events/network_events.cpp.o src/CMakeFiles/FastoTV.dir/client/bandwidth/tcp_bandwidth_client.cpp.o src/CMakeFiles/FastoTV.dir/client/inputs/lirc_input_client.cpp.o  -o build/bin/FastoTV  -rdynamic /usr/local/lib/libfastoplayer.a /usr/local/lib/libfastoplayer_media.a /usr/local/lib/libfastotv_protocol.a /usr/local/lib/libavdevice.a /usr/local/lib/libavformat.a /usr/local/lib/libavfilter.a /usr/local/lib/libavcodec.a /usr/local/lib/libavutil.a /usr/local/lib/libswscale.a /usr/local/lib/libswresample.a /usr/local/lib/libcommon_ev.a /usr/local/lib/libev.a /usr/local/lib/libcommon.a /usr/local/lib/libjson-c.a build/lib/libinih.a /usr/lib/x86_64-linux-gnu/liblirc_client.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbz2.so /usr/lib/x86_64-linux-gnu/libz.so /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a /usr/local/lib/libSDL2.a /usr/local/lib/libSDL2_image.a /usr/local/lib/libSDL2_ttf.a /usr/local/lib/libev.a /usr/local/lib/libcpuid.a -lpthread -ldl -lm /usr/lib/x86_64-linux-gnu/libva-drm.so /usr/lib/x86_64-linux-gnu/libva-x11.so /usr/lib/x86_64-linux-gnu/libSM.so /usr/lib/x86_64-linux-gnu/libICE.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libXext.so /usr/lib/x86_64-linux-gnu/libasound.so -lvdpau -lva /usr/local/lib/libcommon.a /usr/local/lib/libjson-c.a /usr/lib/x86_64-linux-gnu/liblirc_client.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbz2.so /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a /usr/local/lib/libSDL2.a /usr/local/lib/libSDL2_image.a /usr/local/lib/libSDL2_ttf.a /usr/local/lib/libcpuid.a -lpthread -ldl -lm /usr/lib/x86_64-linux-gnu/libva-drm.so /usr/lib/x86_64-linux-gnu/libva-x11.so /usr/lib/x86_64-linux-gnu/libSM.so /usr/lib/x86_64-linux-gnu/libICE.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libXext.so /usr/lib/x86_64-linux-gnu/libasound.so -lvdpau -lva && cd /home/nono/fastotv/build/build_linux/src && /usr/bin/strip --strip-unneeded /home/nono/fastotv/build/build_linux/build/bin/FastoTV
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_initFontMetrics » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:422 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:423 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:424 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:425 : référence indéfinie vers « FT_MulFix »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:426 : référence indéfinie vers « FT_MulFix »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o):/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:427 : encore plus de références indéfinies suivent vers « FT_MulFix »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « Find_Glyph » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:880 : référence indéfinie vers « FT_Get_Char_Index »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « Load_Glyph » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:552 : référence indéfinie vers « FT_Load_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:633 : référence indéfinie vers « FT_Get_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:634 : référence indéfinie vers « FT_Stroker_New »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:650 : référence indéfinie vers « FT_Render_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:846 : référence indéfinie vers « FT_Done_Glyph »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:627 : référence indéfinie vers « FT_Outline_Transform »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:638 : référence indéfinie vers « FT_Stroker_Set »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:639 : référence indéfinie vers « FT_Glyph_Stroke »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:640 : référence indéfinie vers « FT_Stroker_Done »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:642 : référence indéfinie vers « FT_Glyph_To_Bitmap »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:644 : référence indéfinie vers « FT_Done_Glyph »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_SizeUTF8_Internal » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1205 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_CloseFont » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:889 : référence indéfinie vers « FT_Done_Face »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_Init » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:225 : référence indéfinie vers « FT_Init_FreeType »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_OpenFontIndexRW » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:316 : référence indéfinie vers « FT_Open_Face »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:355 : référence indéfinie vers « FT_Set_Charmap »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:397 : référence indéfinie vers « FT_Select_Size »
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:376 : référence indéfinie vers « FT_Set_Char_Size »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Solid » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1345 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Shaded » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1522 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Blended » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1679 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_RenderUTF8_Blended_Wrapped » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1944 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_GetFontKerningSize » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:2093 : référence indéfinie vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o):/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:2125 : encore plus de références indéfinies suivent vers « FT_Get_Kerning »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_GlyphIsProvided » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:1123 : référence indéfinie vers « FT_Get_Char_Index »
/usr/local/lib/libSDL2_ttf.a(SDL_ttf.o) : Dans la fonction « TTF_Quit » :
/home/nono/fastotv/build/build_linux_env/SDL2_ttf-2.0.15/SDL_ttf.c:2079 : référence indéfinie vers « FT_Done_FreeType »
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.`
