### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by milankragujevic** [fastogt/fastotv#51]
Hello, do you have Android TV client for set top box? Or with Live Channels app integration that has nice UI? Thanks.

**Comment by topilski** [comment]
Morning @milankragujevic , yes we have in private repositories

**Comment by topilski** [comment]
![IMG_20191128_162407](https://user-images.githubusercontent.com/4686379/72429360-d66d3e00-37a0-11ea-915d-02e71152eb74.jpg)
![20191227_131429](https://user-images.githubusercontent.com/4686379/72429366-d705d480-37a0-11ea-9120-60a2eb116169.jpg)

**Comment by milankragujevic** [comment]
Very nice. I will contact you via email some time.
