### ISSUE TITLE
fastotv crash adding playlist - Android 11

### ISSUE THREAD

**Issue by 00Kush00** [fastogt/fastotv#54]
Crashes adding 34mb playlist, shows channels but crashes adding them. Don't happen with small lists. App don't show group channels to choose some groups and reduce list size.

**Comment by topilski** [comment]
Hello @00Kush00 , seem it is FastoTVLite bug: https://github.com/fastogt/fastotvlite_mobile

**Comment by 00Kush00** [comment]
Sorry
