### ISSUE TITLE
Android TV Version Keeps Crashing

### ISSUE THREAD

**Issue by themak1985** [fastogt/fastotv#65]
Thanks for all your work on this!

Unfortunately I Installed FastoTV, i had to make an account, but then I was not able to log in with that account information.

Uninstalled and installed fastotv lite, no account needed, but when I go to add a playlist, the entire screen goes white and no prompt to add a playlist comes up. 

Android TV 11

**Comment by topilski** [comment]
Hello, you can donwnload our new app CrocOTT, https://play.google.com/store/apps/details?id=com.crocott , FastoTV not supported anymore.
